spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project?useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:cn.wz.mappper/*.xml
  type-aliases-package: cn.wz.pojo

test:
  springboot_mybatisTest: 测试

